server.port=8081

spring.application.name=bff-service

resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=10s

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dittostore.ciamlogin.com/86e0474b-6c7d-4e7b-8343-30ed0fe0bcb7/v2.0/