eureka.client.service-url.defaultZone=http://172.31.21.90:8761/eureka/
spring.config.import=optional:configserver:http://172.31.21.90:8888

spring.rabbitmq.addresses=localhost:5672,localhost:5673
spring.rabbitmq.username=${RABBITMQ_USER:ditto}
spring.rabbitmq.password=${RABBITMQ_PASS:ditto}