spring.application.name=rabbit-admin-service
server.port=8088

spring.rabbitmq.addresses=localhost:5672,localhost:5673
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.config.import=optional:configserver:http://localhost:8888