spring.application.name=pago-service
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/dittostore_pago?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.config.import=optional:configserver:http://localhost:8888

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.prefetch=1

dittostore.rabbitmq.exchanges.direct=pago.direct.exchange
dittostore.rabbitmq.exchanges.topic=pago.topic.exchange
dittostore.rabbitmq.exchanges.dlx=pago.dlx.exchange
dittostore.rabbitmq.routing-keys.estado-prefix=pago.estado

dittostore.rabbitmq.queues.notificacion.name=pago.notificacion.queue
dittostore.rabbitmq.queues.notificacion.dlq=pago.notificacion.dlq
dittostore.rabbitmq.queues.notificacion.routing-key=pago.estado.*

dittostore.rabbitmq.queues.comprobante.name=pago.comprobante.queue
dittostore.rabbitmq.queues.comprobante.dlq=pago.comprobante.dlq
dittostore.rabbitmq.queues.comprobante.routing-key=pago.estado.aprobado

dittostore.rabbitmq.queues.reembolso.name=pago.reembolso.queue
dittostore.rabbitmq.queues.reembolso.dlq=pago.reembolso.dlq
dittostore.rabbitmq.queues.reembolso.routing-key=pago.reembolso.solicitar

dittostore.rabbitmq.retry.max-intentos=3
dittostore.rabbitmq.retry.backoff-ms=2000